DROP TABLE IF EXISTS PUBLIC.REVIEW_REACTIONS;
DROP TABLE IF EXISTS PUBLIC.REVIEWS;
DROP TABLE IF EXISTS PUBLIC.FRIENDS;
DROP TABLE IF EXISTS PUBLIC.FILM_LIKES;
DROP TABLE IF EXISTS PUBLIC.FILM_GENRE;
DROP TABLE IF EXISTS PUBLIC.USERS;
DROP TABLE IF EXISTS PUBLIC.FILM;
DROP TABLE IF EXISTS PUBLIC.MPA;
DROP TABLE IF EXISTS PUBLIC.GENRE;
DROP TABLE IF EXISTS PUBLIC.REACTIONS;

CREATE TABLE PUBLIC.GENRE (
	GENRE_ID BIGINT NOT NULL AUTO_INCREMENT,
	GENRE_NAME CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
);

CREATE TABLE PUBLIC.MPA (
	MPA_ID BIGINT NOT NULL AUTO_INCREMENT,
	MPA_NAME CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT MPA_PK PRIMARY KEY (MPA_ID)
);

CREATE TABLE PUBLIC.REACTIONS (
	REACTION_ID SMALLINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(10) NOT NULL,
	CONSTRAINT REACTIONS_PK PRIMARY KEY (REACTION_ID)
);

CREATE TABLE PUBLIC.FILM (
	FILM_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(100) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	MPA_ID BIGINT,
	CONSTRAINT FILM_PK PRIMARY KEY (FILM_ID),
	CONSTRAINT FILM_FK FOREIGN KEY (MPA_ID) REFERENCES PUBLIC.MPA(MPA_ID) ON DELETE SET NULL
);

CREATE TABLE PUBLIC.USERS (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	EMAIL CHARACTER VARYING(100) NOT NULL,
	LOGIN CHARACTER VARYING(100) NOT NULL,
	NAME CHARACTER VARYING(100) NOT NULL,
	BIRTHDAY DATE,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE PUBLIC.FILM_GENRE (
	FILM_ID BIGINT NOT NULL,
	GENRE_ID BIGINT NOT NULL,
	CONSTRAINT FILM_GENRE_PK PRIMARY KEY (FILM_ID,GENRE_ID),
	CONSTRAINT FILM_GENRE_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID) ON DELETE CASCADE,
	CONSTRAINT FILM_GENRE_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(GENRE_ID) ON DELETE CASCADE
);


CREATE TABLE PUBLIC.FILM_LIKES (
	FILM_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	CONSTRAINT FILM_LIKES_PK PRIMARY KEY (FILM_ID,USER_ID),
	CONSTRAINT FILM_LIKES_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID) ON DELETE CASCADE,
	CONSTRAINT FILM_LIKES_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE PUBLIC.FRIENDS (
	REQUESTER_ID BIGINT NOT NULL,
	ACCEPTER_ID BIGINT NOT NULL,
	STATUS CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT FRIENDS_PK PRIMARY KEY (REQUESTER_ID,ACCEPTER_ID),
	CONSTRAINT FRIENDS_REQ_FK FOREIGN KEY (REQUESTER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE,
	CONSTRAINT FRIENDS_ACC_FK FOREIGN KEY (ACCEPTER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE
);

CREATE TABLE PUBLIC.REVIEWS (
	REVIEW_ID BIGINT NOT NULL AUTO_INCREMENT,
	CONTENT CHARACTER VARYING(100) NOT NULL,
	IS_POSITIVE boolean NOT NULL,
	USER_ID BIGINT NOT NULL,
	FILM_ID BIGINT NOT NULL,
	USEFUL integer DEFAULT 0,
	CONSTRAINT REVIEWS_PK PRIMARY KEY (REVIEW_ID),
	CONSTRAINT REVIEWS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE,
	CONSTRAINT REVIEWS_FILM_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(FILM_ID) ON DELETE CASCADE
);

CREATE TABLE PUBLIC.REVIEW_REACTIONS (
	REVIEW_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	REACTION_ID SMALLINT NOT NULL,
	CONSTRAINT REVIEW_REACTIONS_PK PRIMARY KEY (REVIEW_ID,USER_ID),
	CONSTRAINT REVIEW_REACTIONS_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID) ON DELETE CASCADE,
	CONSTRAINT REVIEW_REACTIONS_REVIEWS_FK FOREIGN KEY (REVIEW_ID) REFERENCES PUBLIC.REVIEWS(REVIEW_ID) ON DELETE CASCADE,
	CONSTRAINT REVIEW_REACTIONS_REACTIONS_FK FOREIGN KEY (REACTION_ID) REFERENCES PUBLIC.REACTIONS(REACTION_ID) ON DELETE CASCADE
);




